import { DrizzleService } from "@/services/drizzle-service.server";
import { createClipOperations } from "@/services/db-clip-operations.server";
import { createVideoOperations } from "@/services/db-video-operations.server";
import { createCourseOperations } from "@/services/db-course-operations.server";
import { createVersionOperations } from "@/services/db-version-operations.server";
import { createLessonSectionOperations } from "@/services/db-lesson-section-operations.server";
import { createLinkAuthOperations } from "@/services/db-link-auth-operations.server";
import { createThumbnailOperations } from "@/services/db-thumbnail-operations.server";
import { createPitchOperations } from "@/services/db-pitch-operations.server";
import { createDiagramOperations } from "@/services/db-diagram-operations.server";
import { createDeliverableOperations } from "@/services/db-deliverable-operations.server";
import { Effect } from "effect";

export class DBFunctionsService extends Effect.Service<DBFunctionsService>()(
  "DBFunctionsService",
  {
    effect: Effect.gen(function* () {
      const db = yield* DrizzleService;

      const {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
      } = createClipOperations(db);

      const {
        getCourseById,
        getCourseByFilePath,
        getCourseWithSectionsById,
        getCourseStructureById,
        getCourseNavigationData,
        getCourseWithSlimClipsById,
        getVideoTranscripts,
        getCourseWithSectionsByFilePath,
        getCourses,
        getTopActiveCourses,
        getArchivedCourses,
        createCourse,
        createGhostCourse,
        updateCourseName,
        updateCourseMemory,
        updateCourseArchiveStatus,
        updateCourseFilePath,
        deleteCourse,
        duplicateCourse,
      } = createCourseOperations(db);

      const {
        getReferenceVideoCandidates,
        getVideoDeepById,
        getStandaloneVideos,
        getStandaloneVideosSidebar,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        getVideoWithClipsById,
        getVideoWithLessonById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        updateVideoArchiveStatus,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getVideosForFewShotExamples,
      } = createVideoOperations(db, {
        getCourseNavigationData,
      });

      const {
        getCourseVersions,
        getLatestCourseVersion,
        getCourseVersionById,
        getCourseWithSectionsByVersion,
        getCourseWithSectionsByVersionSlim,
        getVersionWithSections,
        createCourseVersion,
        updateCourseVersion,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
      } = createVersionOperations(db);

      const {
        getLessonById,
        getLessonsBySectionId,
        getLessonWithHierarchyById,
        getSectionWithHierarchyById,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        archiveSection,
        updateSectionOrder,
        updateSectionPath,
        updateSectionDescription,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
        batchUpdateLessonOrders,
        batchUpdateSectionOrders,
      } = createLessonSectionOperations(db);

      const {
        getLinks,
        createLink,
        deleteLink,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
      } = createLinkAuthOperations(db);

      const {
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        deleteThumbnail,
      } = createThumbnailOperations(db);

      const {
        createPitch,
        listPitches,
        listPitchesWithVideos,
        getPitch,
        getPitchWithVideos,
        updatePitchField,
        createVideoFromPitch,
        deletePitch,
      } = createPitchOperations(db);

      const {
        listDeliverables,
        createDeliverable,
        updateDeliverableStatus,
        updateDeliverable,
        duplicateDeliverable,
        archiveDeliverable,
      } = createDeliverableOperations(db);

      const {
        createDiagram,
        listDiagrams,
        getDiagram,
        updateDiagram,
        updateDiagramHead,
        createSnapshot,
        getDiagramSnapshot,
        listSnapshots,
        listSnapshotsWithClips,
        listAllSnapshotsWithClips,
        setSnapshotArchived,
        restoreSnapshotToHead,
        createSnapshotForClip,
        updateClipDiagramPin,
      } = createDiagramOperations(db);

      return {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
        getLessonById,
        getLessonWithHierarchyById,
        getLessonsBySectionId,
        getSectionWithHierarchyById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        getCourseById,
        getCourseByFilePath,
        getCourseWithSectionsById,
        getCourseStructureById,
        getCourseWithSlimClipsById,
        getVideoTranscripts,
        getCourseWithSectionsByFilePath,
        getCourses,
        getTopActiveCourses,
        getArchivedCourses,
        getReferenceVideoCandidates,
        getVideoById: getVideoDeepById,
        getVideoWithClipsById: getVideoWithClipsById,
        getVideoWithLessonById: getVideoWithLessonById,
        getStandaloneVideos,
        getStandaloneVideosSidebar,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        createCourse,
        createGhostCourse,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        archiveSection,
        updateSectionOrder,
        updateSectionPath,
        updateSectionDescription,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
        batchUpdateLessonOrders,
        batchUpdateSectionOrders,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getCourseVersions,
        getLatestCourseVersion,
        getCourseVersionById,
        getCourseWithSectionsByVersion,
        getCourseWithSectionsByVersionSlim,
        getVersionWithSections,
        createCourseVersion,
        updateCourseVersion,
        updateCourseName,
        updateCourseMemory,
        updateCourseArchiveStatus,
        updateVideoArchiveStatus,
        updateCourseFilePath,
        deleteCourse,
        duplicateCourse,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
        getLinks,
        createLink,
        deleteLink,
        getVideosForFewShotExamples,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        deleteThumbnail,
        createPitch,
        listPitches,
        listPitchesWithVideos,
        getPitch,
        getPitchWithVideos,
        updatePitchField,
        createVideoFromPitch,
        deletePitch,
        createDiagram,
        listDiagrams,
        getDiagram,
        updateDiagram,
        updateDiagramHead,
        createSnapshot,
        getDiagramSnapshot,
        listSnapshots,
        listSnapshotsWithClips,
        listAllSnapshotsWithClips,
        setSnapshotArchived,
        restoreSnapshotToHead,
        createSnapshotForClip,
        updateClipDiagramPin,
        listDeliverables,
        createDeliverable,
        updateDeliverableStatus,
        updateDeliverable,
        duplicateDeliverable,
        archiveDeliverable,
      };
    }),
  }
) {}
